### ISSUE TITLE
Support `.gitignore`

### ISSUE THREAD

**Issue by evilebottnawi** [kucherenko/jscpd#100]
Be great allow usage `--ignore-path .gitignore` (alias `exclude` option in config file) as doing `eslint`, `stylelint` and etc linters (`node-ignore` package). It is allow exclude files in one way for many package without duplicate code. Thanks!

**Comment by kucherenko** [comment]
Thank you for feature request, will try to add this in new version of jscpd

**Comment by kucherenko** [comment]
Implemented in jscpd@1.0.0
