### ISSUE TITLE
How to change min size of duplication in code in jscpd

### ISSUE THREAD

**Issue by ssunny2** [kucherenko/jscpd#103]
Hi,

I tried changing the minimum size from the default(5) to 1 using the following commands in gitBash for a test project with two components:

jscpd C:\Users\sherin.sunny\Desktop\test --languages typescript --min-lines=1 --output report.xml
jscpd -l 1 C:\Users\sherin.sunny\Desktop\test --languages typescript --output report.xml

However, any duplication below 5 lines weren't getting reflected in the generated report. I'm new to this and need help.

**Comment by kucherenko** [comment]
thank you for the report

min-lines not just one parameter for set duplication block size, you can try to set min-tokens parameter for make duplication block smaller

**Comment by ssunny2** [comment]
Hello Kucherenko,

Sorry for bothering you again, I'm able to successfully generate reports in xml format using "jscpd --output report.xml" command. However, I'm not able to get an HTML report using "jscpd --output report.html". 

could you help a bit on how to use "jscpd -x reporters-xslt/simple.xsl -p test/fixtures/ -r xml -o report.xml" to generate report in HTML format.

**Comment by kucherenko** [comment]
Hello
When you add path to xsl you have xml file with attached xsl. If you open the xml file in a browser you will have generated html right in the browser.

**Comment by ssunny2** [comment]
ok. and what's the difference between min-lines and min-tokens if both these parameters are used for setting duplication block size and why both of them need to be configured in the .cpd.yaml file?

**Comment by kucherenko** [comment]
a token is an atomic value of source code, for example, the following line:

const a = "hello" 

has 4 tokens "const" - reserved word, "a"  -  variable name,  "=" - operator, "hello" - string
