### ISSUE TITLE
Feature request: Create a netbeans plugin.

### ISSUE THREAD

**Issue by Chris2011** [kucherenko/jscpd#11]
I use Netbeans for my daily work, I can use this plugin with grunt for JS but I have to use a lot other languages like C/C++ or Java or PHP so what I would like to have is a plugin for netbeans where I can have options and where I can detect duplicated code for one language or more languages inside one project or multiple projects, that would be great.

**Comment by kucherenko** [comment]
Thank you for request.

I think it is good idea, but for now I have no time for implement it, I hope I will do it in future.

**Comment by Chris2011** [comment]
No Problem if you will start with this, let me know it, so we can talk about the features maybe :).
