### ISSUE TITLE
report.coffee stops before writting the report into the output file

### ISSUE THREAD

**Issue by lgraziani2712** [kucherenko/jscpd#128]
If the threshold is surpased, JsCpd exits with an error, but it doesn't write anything.

It would be expected to have the duplication report file even when the threshold is surpased (even more important when that happens).

This files are responsible for the bug;

https://github.com/kucherenko/jscpd/blob/918bc70b215a6e3e934b58b59cc65aff29bf0afd/src/jscpd.coffee#L50

https://github.com/kucherenko/jscpd/blob/918bc70b215a6e3e934b58b59cc65aff29bf0afd/src/reporters/_std-log.coffee#L83

Thank you for your work!

**Comment by kucherenko** [comment]
Thank you for bug report! Will fix it soon

**Comment by kucherenko** [comment]
fixed in jscpd@0.6.20
