### ISSUE TITLE
What are valid blame values?

### ISSUE THREAD

**Issue by splintor** [kucherenko/jscpd#129]
The documentation says `blame` accepts a `BOOLEAN` but there is no sample on what it needs to activate blame. Is it `on`? `1`? `true`? `TRUE`?
An example would be very useful.
(The blame screenshot doesn't show the command line :( )

**Comment by kucherenko** [comment]
The example of .cpd.yaml:
`exclude:
  - "**/fixtures/**/*"
  - "**/node_modules/**"
blame: true
`
Also you can start `jscpd --blame` in terminal

**Comment by kucherenko** [comment]
Looks like you don't have installed git on your Windows PC or your current working dir is not under git.
