### ISSUE TITLE
blame report to JSON

### ISSUE THREAD

**Issue by Dipen-Dedania** [kucherenko/jscpd#131]
First of all, awesome work with the package. I'm running jscpd with below code

`jscpd --path ./src --blame true --reporter json --output report.json`

I'm not able to get Author details in output JSON, though it's visible in CLI

![jscpd](https://user-images.githubusercontent.com/5135662/36775140-d180fa76-1c86-11e8-8b7d-e767988c3590.PNG)

**Comment by kucherenko** [comment]
thank you for reporting, I will investigate the issue. Currently json reporter does not support blame authors

**Comment by kucherenko** [comment]
jscpd@1.0.0 supports blamed report in JSON
