### ISSUE TITLE
jscpd: Unhandled rejection TypeError: Cannot set property 'author2' of undefined

### ISSUE THREAD

**Issue by mboughaba** [kucherenko/jscpd#137]
I am not able to generate html report with blame option active. I get the error:
`Unhandled rejection TypeError: Cannot set property 'author2' of undefined` I suspect it is not able to find the author of git commit of the duplicated (2) file.

Did anyone run into the same issue?

Cheers

**Comment by kucherenko** [comment]
thank you for reporting, but currently blame option not supported for html report, sorry

**Comment by kucherenko** [comment]
In version jscpd@1.0.0 you can find blamed lines in json reporter
