### ISSUE TITLE
Snyk security vulnerability (shelljs dependency) 

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#139]
A security vulnerability is being notified for users of `jscpd` because it depends on the `shelljs` dependency which has a [security vulnerability](https://snyk.io/vuln/npm:shelljs:20140723).

At the moment it seems like `shelljs` is only used for `shelljs.cat` and `shelljs.test`. In which case this might be solved by using core modules `fs.readFile` and `fs.stat` (and their synchronous variants).

Thanks for your work on this project, it's very useful.

**Comment by kucherenko** [comment]
thank you, will fix soon
