### ISSUE TITLE
Output file not getting generated in windows

### ISSUE THREAD

**Issue by siliconhobbyist** [kucherenko/jscpd#143]
I'm trying to generate the output report file on windows, however, there is no file that is generated in the given location

Here's what I'm trying and the output I'm getting, the path till 'bin' directory is already created. :

D:\somepath\s\c>jscpd --output D:\somepath\bin\report.xml
info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
info:    Preprocessors running time: durationMs=9
info:    Scanning 3 files for duplicates...
info:    Scanning for duplicates time: durationMs=71
info:    Scanning... done!

info:    Start report generation...

Found 2 exact clones with 34 duplicated lines in 2 files

        - D:\somepath\s\c\a.ts: 5-19
         D:\somepath\s\c\a.ts: 6-20

        - D:\somepath\s\c\a.ts: 1-21
         D:\somepath\s\c\d\d.ts: 6-26

 53.13% (34 lines) duplicated lines out of 64 total lines of code.

ERROR: jscpd found too many duplicates over threshold

**Comment by siliconhobbyist** [comment]
Also tried to give relative path, paths in quotes, it didn't work. Maybe I'm missing something simple?

**Comment by kucherenko** [comment]
you are right, I will fix the issue in future

**Comment by kucherenko** [comment]
fixed at jscpd@0.6.21
