### ISSUE TITLE
Missing ability to ignore empty lines, trailing spaces and indentation

### ISSUE THREAD

**Issue by evgygor** [kucherenko/jscpd#151]
Hello,
maybe it already exists and I just missed, but It would be nice to have abilities:

- Ignore empty lines
- Ignore trailing spaces
- Ignore whole indentation (leading spaces, tabs..)

Below duplicated examples, but due empty lines, wrong indentation, trailing spaces, not fully detected
**Code 1**

             if(m.global.User_auto_auth = "on")
             
                 m.basicLogin_stage = m.top.createChild("BasicLoginyes")
                 m.basicLogin_stage.SetFocus(true)
                 m.basicLogin_stage.ObserveField("token", "tokengen")
                 m.basicLogin_stage.ObserveField("View","viewAsGuestSelected")
                 m.basicLogin_stage.ObserveField("error_return","Errorreturned" )
                 
             else 
                e = m.ip_auth.Error_code
                r = m.ip_auth.response
                
                errorString1 = "Error Code=700, Error Message=  " + r.ToStr() + " Error" + Chr(91) + e.ToStr() +  Chr(93)
                m.top.statusMessage = errorString1
                m.top.error_return = true
                
            end if 
            
        m.ip_auth.control="DONE"

**Code 2**

             if(m.global.User_auto_auth = "on")
                 m.basicLogin_stage = m.top.createChild("BasicLoginyes")
                 m.basicLogin_stage.SetFocus(true)
                 m.basicLogin_stage.ObserveField("token", "tokengen")
                 m.basicLogin_stage.ObserveField("View","viewAsGuestSelected")
                 m.basicLogin_stage.ObserveField("error_return","Errorreturned" )
                 
             else 
                e = m.ip_auth.Error_code
                r = m.ip_auth.response
                
                errorString1 = "Error Code=700, Error Message=  " + r.ToStr() + " Error" + Chr(91) + e.ToStr() +  Chr(93)
                m.top.statusMessage = errorString1
                m.top.error_return = true
                
            end if 
            m.ip_auth.control="DONE" 

### Actually detected code:

**JSCPD CLI:**
C:\Git_work\main\DFW\components\Authn> jscpd --files="**/auto_authn.brs" --languages-exts="python:brs"
info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
info:    Preprocessors running time: durationMs=24
info:    Scanning 1 files for duplicates...
info:    Scanning for duplicates time: durationMs=66
info:    Scanning... done!

info:    Start report generation...

info:    Found 2 exact clones with 20 duplicated lines in 1 files

        - C:\Git_work\main\DFW\components\Authn\auto_authn.brs: 52-64
         C:\Git_work\main\DFW\components\Authn\auto_authn.brs: 78-90

        - C:\Git_work\main\DFW\components\Authn\auto_authn.brs: 155-163
         C:\Git_work\main\DFW\components\Authn\auto_authn.brs: 168-176

 6.62% (20 lines) duplicated lines out of 302 total lines of code.

**jscpd-vscode visualization:**

![image](https://user-images.githubusercontent.com/10452376/42153475-e3fcd7da-7deb-11e8-90f1-cb4282a06573.png)

**Comment by kucherenko** [comment]
thank you for the report, I will investigate

**Comment by kucherenko** [comment]
Implemented in alpha version of jscpd

`npm install jscpd@1.0.0-alpha.2`

And run 
`jscpd --mode weak path/to/code/`

All comments, whitespaces will be ignored
