### ISSUE TITLE
Language extension mapping doesn't seem to work

### ISSUE THREAD

**Issue by matthew-dean** [kucherenko/jscpd#155]
We have all our React files as `.js`. However, this doesn't seem to work:

```
jscpd -p src/ --languages jsx --languages-exts jsx:js
```
If we write this, it runs jscpd, but using javascript vs jsx:
```
jscpd -p src/ --languages javascript
```

**Comment by kucherenko** [comment]
thank you for the report, will check

**Comment by kucherenko** [comment]
language mapping implemented in the alpha version of jscpd.

You can try to install `npm i jscpd@1.0.0-alpha.2 -g` and use right mapping.
