### ISSUE TITLE
Exclude multiple directories with command line

### ISSUE THREAD

**Issue by rap2hpoutre** [kucherenko/jscpd#163]
Is there a way to exclude multiple directories from command line only? (example: exclude `node_modules` and `build` directory).

**Comment by kucherenko** [comment]
Thank you for reporting.
You can use jscpd RC with the following options
```
npx jscpd@1.0.0-rc.0 --ignore "**node_modules**,**build**" /path/to/code
```
Also, you can skill all lines from gitignore with following options:
```
npx jscpd@1.0.0-rc.0 --gitignore /path/to/code
```

**Comment by rap2hpoutre** [comment]
Thank you!
