### ISSUE TITLE
Is running on Windows supported?

### ISSUE THREAD

**Issue by ocioran** [kucherenko/jscpd#165]
Hi,

I installed jscpd and tried to run it on windpws, but all I got was the help message from the node. I was not even able to get jscpd help message.
Is running on windows supported?

Thanks,
Olga

**Comment by ocioran** [comment]
It seems to work from node.js command prompt, but not from plain cmd or plain node.js

**Comment by kucherenko** [comment]
I guess you can try to run `jscpd` with following command:
```
npx jscpd {list of options}
```

**Comment by kucherenko** [comment]
Try to install the last version of jscpd and run again
