### ISSUE TITLE
(feature)Disabling whole file with one comment

### ISSUE THREAD

**Issue by wjureczkaPracuj** [kucherenko/jscpd#172]
Hey, 
Thank you for such a great tool! I would like to suggest some feature. I know there is a tokens that can ignore some blocks( jscpd:ignore-end,  jscpd:ignore-start). Therefore, it would be lovely if jscpd could have such token to ignore whole file(like in the config).

WDYF?

Cheers

**Comment by kucherenko** [comment]
Thank you for feedback. 

Currently, you can write mode and filter not needed tokens. However, it is a good idea and I will add `custom` mode with a config for that.

**Comment by kucherenko** [comment]
Added the feature to master branch, will be in next release

**Comment by wjureczkaPracuj** [comment]
Nice! I appreciate your work, thank you.
