### ISSUE TITLE
Fail to map options.path

### ISSUE THREAD

**Issue by Kermit-Xuan** [kucherenko/jscpd#177]
The first path is true(invalid) in `options.path` and it appears error when running `path.substr`.

![image](https://user-images.githubusercontent.com/33770367/49002542-d5dba780-f19a-11e8-8a9e-c5e73f871ce3.png)

**Comment by kucherenko** [comment]
Hello, thank you for the report.

As I can see you are going to use an old version of cli options for running the jscpd.
In jscpd@1.0.0 the following options are changed:
`-p, --path` options is deprecated
`--skip-comments` - is not supported, use `--mode weak` for skip comments 
`--limit` - is not supported, use `--threshold 1` for check copy/paste level 

So, you can run your script in the following way:
```
jscpd src -b --verbose -l 15 --threshold 1 --mode weak
```

**Comment by Kermit-Xuan** [comment]
OK, thank you very much.

**Comment by kucherenko** [comment]
Fixed in  jscpd@1.0.3
