### ISSUE TITLE
BAD npm dependency: gitignore-to-glob is not under active development

### ISSUE THREAD

**Issue by ankur-bambharoliya** [kucherenko/jscpd#179]
`gitignore-to-glob` has quite a few issues and misses some important patterns for example https://github.com/EE/gitignore-to-glob/pull/6. Moreover, the contributors are not active and few useful PRs are open for more than a year. I think it better to get rid of such a dependency or contact the contributor to merge those PRs.

**Comment by kucherenko** [comment]
thank you, fixed in jscpd@1.0.1
