### ISSUE TITLE
Ignore lines that match a pattern

### ISSUE THREAD

**Issue by akinnee** [kucherenko/jscpd#18]
For example, I'd like to ignore require statements and module.export statements since those are repetitive by nature.

Example, the following code is duplicated in two of my files, but I think that's perfectly fine:

```
var
    _ = require('underscore'),
    Backbone = require('backbone'),
    LayoutView = require('LayoutView'),
    Moment = require('moment'),

    appVent = require('appVent'),
    format = require('format'),
    pluginAPI = require('pluginAPI'),

    personalAccountAppsTemplate = require('personalAccountAppsTemplate'),
    personalAccountAppsListEmptyTemplate = require('personalAccountAppsListEmptyTemplate'),
```

**Comment by kucherenko** [comment]
thank you, I'll look on it

**Comment by akinnee** [comment]
Awesome. I really appreciate it. This tool is super useful.

**Comment by voitau** [comment]
+1. What about something like they have in jshint:
```javascript
/* jshint ignore:start */
// Code here will be ignored by JSHint.
/* jshint ignore:end */
```

**Comment by akinnee** [comment]
I think that requiring the same modules in multiple files is so common that it should automatically be ignored.

**Comment by bosvos** [comment]
Great tool.
+1 for ignore patterns in code or automatic ignore for imports in e.g. java.

**Comment by potatopankakes** [comment]
`jsinspect` automatically ignores `require()`, but also has the same feature request... namely, to be able to mark certain sections to ignore.  both of these features would be a useful feature in `jscpd`.

**Comment by diegokogan** [comment]
+1 for something like jshint comment-style deactivation.

**Comment by poligarcia** [comment]
+1

**Comment by lalo73** [comment]
+1

**Comment by nahdelgado** [comment]
+1

**Comment by ryansmith94** [comment]
Created PR #86 for this.

**Comment by kucherenko** [comment]
Implemented in the alpha version of jscpd

You can install `npm i jscpd@1.0.0-alpha.2 -g` 

And mark ignores blocks in the following style:

```
// jscpd:ignore-start
you ignored code here 
// jscpd:ignore-end
not ignored code
```
The comment should use in the style of languages, it can be `#, //, /* */, <!-- -->`

**Comment by alsheuski** [comment]
@kucherenko I think what possibility to describe excluding lines through regex pattern in one single file should be very useful. In case you need to check legacy codebase and you can't surround duplicates in each file manually.

**Comment by llwt** [comment]
@kucherenko Has the programmatic API been implemented yet? We're facing the same thing where we'd like to ignore `import ... from ...` lines.
