### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, scandir '/.DocumentRevisions-V100'

### ISSUE THREAD

**Issue by yuthecub** [kucherenko/jscpd#186]
I'm very new to node.js and this and have tried very hard to understand what has happened. Please pardon me if I'm asking stupid questions.

After installation, I run this basic command to try it out and this happened

**Screenshots**
![image](https://user-images.githubusercontent.com/21239352/50549840-1a2cfc80-0c9f-11e9-9f84-d4524d35735e.png)

**Desktop (please complete the following information):**
 - OS: [macOS Mojave]
 - OS Version [10.14.2]
 - NodeJS Version [10.15.0]

**Comment by kucherenko** [comment]
Looks like you are going to find duplications starts from root folder, try to run following command for detect duplications in php files:

‘’’
jscpd . —format php
‘’’
