### ISSUE TITLE
Header file "duplicates" the c file

### ISSUE THREAD

**Issue by cdown** [kucherenko/jscpd#188]
Firstly, thanks for the tool.

While of course *technically* jscpd is correct, this is obviously not desirable:

![2019-01-03_170812_350020113](https://user-images.githubusercontent.com/660663/50651138-62d40680-0f7a-11e9-925b-56fee0bd1744.png)

Header files are an inherent part of how the C language works, so it seems silly to point this out.

This is with 2.0.2 on the systemd source (current master), called with `-r html -f c -g`.

**Comment by kucherenko** [comment]
thank you for the report, I will try to make improvement related to the issue

**Comment by kucherenko** [comment]
Fixed in jscpd@2.0.4, с and h files marked as separated formats: `c` and `c-header`
