### ISSUE TITLE
formatsExts not work in config file

### ISSUE THREAD

**Issue by vchenchong** [kucherenko/jscpd#193]
**Describe the bug**
'formatsExts' value in .jscpd.json was ignored event when no cli option was input.

**To Reproduce**
/jscpd/src/utils/options.ts:
In function prepareOptions, argsConfig parsed from cli options has higher priority than storedConfig parsed from .jsoncpd.json. But function parseFormatsExtensions will return an empty object which will override the value parsed from .jsoncpd.json even when cli option is empty.

**Expected behavior**
If there is no cli option, config in .jsoncpd.json always works as expected.

**Screenshots**

**Desktop (please complete the following information):**
 - jscpd version [2.0.4]

**Comment by kucherenko** [comment]
thank you for the report, will fix it

**Comment by kucherenko** [comment]
fixed at jscpd@2.0.8
