### ISSUE TITLE
Add flag to ignore text's case

### ISSUE THREAD

**Issue by evgygor** [kucherenko/jscpd#195]
**Is your feature request related to a problem? Please describe.**
It would be nice to have ability ignore text casing when looking for duplication

**Describe the solution you'd like**
Relevant CLI flag

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kucherenko** [comment]
Thank you for the feature request, I'll add it as the point to the todo list

**Comment by kucherenko** [comment]
May I ask for more details about the format of detection?

**Comment by evgygor** [comment]
> May I ask for more details about the format of detection?
The following block of code I expected for detection of 6 lines of code when appropriate flag used (--ignore-case)

`function foo()
    m.global.addFields({stagetoken : ""})
    m.global.addFields({ip_appid : ""})
    m.global.addFields({ip_userID :""})
    m.global.addFields({optedIn_userID :""})
    m.global.addFields({webtoken : ""})
    m.global.addFields({AA_feild :""})


    'Duplication 

    m.GLOBAL.addFields({stagetoken : ""})
    m.GLOBAL.addFields({ip_appid : ""})
    m.GLOBAL.addFields({ip_userID :""})
    m.GLOBAL.addFields({optedIn_userID :""})
    m.GLOBAL.addFields({webtoken : ""})
    m.GLOBAL.addFields({AA_feild :""})
end function
`

**Comment by kucherenko** [comment]
fixed at jscpd@2.0.9

**Comment by evgygor** [comment]
> fixed at jscpd@2.0.9

Thanks a lot!
