### ISSUE TITLE
OOM - can't handle large projects without arbitrarily low file size limits

### ISSUE THREAD

**Issue by paulgerlich-wf** [kucherenko/jscpd#197]
**Describe the bug**
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**To Reproduce**
Ran on a dart repository to get an idea of effectiveness. 

**Expected behavior**
A report is generated

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: Not relevant
 - NodeJS Version: v11.6.0
 - jscpd version: 2.0.4

**Additional context**
Ran it on a decent sized dart repository with default settings. Bombed out after some time. Running on a 16gb RAM machine.

Is there a method for allowing it to rotate cache / pattern DB from disk?

**Comment by kucherenko** [comment]
Do you have any details about the issue, is it actual now?

**Comment by pgerlich** [comment]
Ended up verifying it was a non-issue, just had to extend NPMs memory. I opened another issue though
