### ISSUE TITLE
Does not properly detect code duplication with over_react and dart

### ISSUE THREAD

**Issue by paulgerlich-wf** [kucherenko/jscpd#198]
**Describe the bug**
Code duplication detection does not work, at all, with over react. It thinks that each statically typed react component is duplication because the component name is the same.

**To Reproduce**
Look at the [over_react](https://github.com/Workiva/over_react) codebase and run the jscpd on the examples directory.

**Expected behavior**
Real code duplication is detected.

**Screenshots**
<img width="388" alt="screen shot 2019-02-11 at 9 14 10 am" src="https://user-images.githubusercontent.com/16763427/52576498-6d858500-2ddd-11e9-9977-f62ddb3f2fa0.png">

**Desktop (please complete the following information):**
 - OS: NA
 - OS Version: NA
 - NodeJS Version: NA
 - jscpd version: latest

**Additional context**
This applies basically everywhere

**Comment by kucherenko** [comment]
Thank you for the report, will investigate

**Comment by kucherenko** [comment]
I've investigated the repo and did't find the code from the screenshot.

In general, I can say, that jscpd detect similar parts in code and show them in a report. I've ran jscpd on over_react repo and check report, all results were correct. 

If you are interested in the detection algorithm you can read about Rabin-Karp algorithm, jscpd implement it.
