### ISSUE TITLE
Feature: Flag for failure exit code

### ISSUE THREAD

**Issue by nonlux** [kucherenko/jscpd#20]
For continuous integration support `jscpd` should return failure exit code.

**Comment by kucherenko** [comment]
Good idea, I think it can be property in config, something like percentage of duplication lines for build.

I'll take a look

**Comment by nonlux** [comment]
I'd like this tool and  I want to help. 
But  I don`t  use coffeescript (.

**Comment by voitau** [comment]
+1

**Comment by kucherenko** [comment]
already implemented in ^0.5.4, you can use --limit option for point needed level of duplications
