### ISSUE TITLE
Make `level` dependency installation optional

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#202]
First thanks for this module, I use it a lot and it's great work!

**Is your feature request related to a problem? Please describe.**
`level` uses `leveldown` which is a native module. Installing this native module is slow and can more than double the time required by `npm install` on a project. Considering the code provides alternative stores such as files and in-memory, there should be a way to opt-out of installing this native module.

I am not 100% sure but I am assuming stores are used to cache results between different runs (correct me if I'm wrong). If so I think faster read/writes or smaller cache size are nice-to-have, but I am not sure this justifies doubling the time required by `npm install`.

**Describe the solution you'd like**
Any solution works, but one that might work would be:
  - try to `require('level')`. If this throws, use `require('level-js')` instead
  - replace `level` by `level-js` in `package.json` `dependencies`

I.e. to use the native module, `level` must be manually installed by users.

**Describe alternatives you've considered**
`optionalDependencies` do not work here because they are still installed and are meant for a different purpose.

**Comment by kucherenko** [comment]
Thank you for the report. I will solve the issue, I guess separately installed packages for leveldb and jscpd will be a good solution.
I have investigated `level-js` package and as I can see it depends on indexedDB and works only in a browser.

**Comment by kucherenko** [comment]
About stores: stores are not used for cache results between runs, it is used for detection base on Rabin-Karp algorithm. 
LevelDB was added for solve issue with memory overflow.

**Comment by ehmicky** [comment]
Good point about `level-js` depending on IndexedDB, i.e. my solution cannot work.

Thanks also for explaining the reasoning both behind stores and LevelDB.

If I understand correctly LevelDB was used to fix issues related to (really really) big repositories (#184) (i.e. ElasticSearch codebase). This leads me to wonder:
  - the vast majority of users won't run into this memory overflow, i.e. should they be required to install that native module?
  - for those users wouldn't the `memory` store also be faster?

**Comment by kucherenko** [comment]
It makes sense to make separate levelDB package for checking big repos. I think I will do that

**Comment by ehmicky** [comment]
Just for information purpose: I've tried each store on a [medium-size repository](https://github.com/ehmicky/autoserver) and got the following average times: 20 seconds for `level` and 15 seconds for both `memory` and `files`. 

Another perk for `memory` is that it does not create `.jscpd` folder, although that's not a huge issue (just need to add it to `.gitignore`).

**Comment by ehmicky** [comment]
This issue is not a problem anymore. `leveldown@5` uses N-API and the installation time is now much faster.
