### ISSUE TITLE
Add `--min-tokens` CLI option

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#203]
**Is your feature request related to a problem? Please describe.**
The `minTokens` option is available programatically or through the configuration file, but not as a CLI option.

**Describe the solution you'd like**
Add the `--min-tokens` CLI option.

**Comment by kucherenko** [comment]
https://github.com/kucherenko/jscpd/issues/190 cloned issue

**Comment by ehmicky** [comment]
Sorry!

**Comment by kucherenko** [comment]
NP.
The report can help me to prioritize the issues.
Thank you
