### ISSUE TITLE
Source maps are invalid

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#205]
**Describe the bug**
Source maps are invalid.

It's visible when trying to use them while debugging in Chrome developer tools. The Chrome developer tools show that the source map is found. However the source code does not show up.

For example the source map for `jscpd.js` (which is inlined as base64 in the bottom of that file) looks like this:
```json
{
  "version":3,
  "file":"jscpd.js",
  "sourceRoot":"",
  // This should be `../jscpd.ts` instead
  "sources":["../src/jscpd.ts"],
  // This should not be empty
  "names":[],
  "mappings":";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;AAAA,skipped for the example"
}
```

**To Reproduce**
  - install `jscpd` as a dependency
  - run it using `node --inspect-brk`
  - open Chrome developer tools debugger
  - when stepping inside `jscpd`, the debugger does not show the source code

**Expected behavior**
Debugger should show the source code

**Desktop (please complete the following information):**
 - OS: Linux
 - OS Version: `18.10`
 - NodeJS Version: `11.10.0`
 - jscpd version: `2.0.9`

**Additional information**
This is a separate topic but the source map is inlined, which almost doubles the size of the `npm` bundle, making `npm install` and `require()` a little slower. I think using external source maps would solve this issue though.

I would offer to help with this issue, however I think source mapping is done with the `tsconfig.json` and I'm unfortunately not familiar with this.

**Comment by kucherenko** [comment]
I recommend using ts-node for debugging the source.
More information you can try to find in the following article:
https://medium.com/@dupski/debug-typescript-in-vs-code-without-compiling-using-ts-node-9d1f4f9a94a

**Comment by ehmicky** [comment]
Thanks this solves my problem. 

However generally speaking users might want to debug their dependencies without installing tools specific to those dependencies (e.g. TypeScript-specific debugging). Here the source map `sources` property is invalid according to the [source map specification](https://sourcemaps.info/spec.html#h.mofvlxcwqzej). I don't know TypeScript so I'm not sure if this is an issue with the TypeScript configuration or with TypeScript itself (although I am guessing the second one is less likely).

If you don't think this is an issue though, feel free to close this issue. Thanks!
