### ISSUE TITLE
Possible bug with the `min-lines` option

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#206]
**Describe the bug**
This is not a bug report but a report of dead code which might create a potential bug (although I am not sure of that).

In [`detector.ts`](https://github.com/kucherenko/jscpd/blob/master/src/detector.ts#L63) `clones.filter()` is called but not assigned not returned. `Array.filter()` does not modify its arguments. Instead it creates a new array, i.e. `clones.filter()` is a noop here. I think this is probably not intended.

**To Reproduce**
I cannot reproduce because I'm not sure what the bug is (if there is any).

**Comment by kucherenko** [comment]
Excellent! Thank you for deep dive in the code. 
It is really dead code and I've seen the result in a report with one line of duplication.

**Comment by kucherenko** [comment]
fixed in jscpd@2.0.10
