### ISSUE TITLE
What priority? Config or  console options?

### ISSUE THREAD

**Issue by nonlux** [kucherenko/jscpd#21]
At now config rewrite console options.
I think more usability will be when options rewrite config.
Example:
 - I use  my  default values  for tokens and lines in config file.
 -  If I want to check some  other values one time, I should edit config.

It is slow workflow ))

**Comment by kucherenko** [comment]
Thank you, I will change priority in new version, also I going to add --config option for customize config file

**Comment by b-long** [comment]
:+1:

**Comment by kucherenko** [comment]
Now console options has biggest priority (version 0.5.0)
