### ISSUE TITLE
Cannot read property 'formats' of undefined

### ISSUE THREAD

**Issue by kentmz** [kucherenko/jscpd#213]
**Describe the bug**
When I run the command:
jscpd D:\code -f "css" -r "html"
I get the following exception

> (node:10048) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'formats' of undefined
    at HtmlReporter.report (\npm\node_modules\jscpd\build\reporters\html.js:27:52)
    at \npm\node_modules\jscpd\build\jscpd.js:375:38
    at Array.map (<anonymous>)
    at JSCPD.<anonymous> (\npm\node_modules\jscpd\build\jscpd.js:374:77)
    at step (\npm\node_modules\jscpd\build\jscpd.js:43:23)
    at Object.next (\npm\node_modules\jscpd\build\jscpd.js:24:53)
    at fulfilled (\npm\node_modules\jscpd\build\jscpd.js:15:58)
    at <anonymous>
(node:10048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The folder D:\code contains only css files.

**Expected behavior**
Should provide a user friendly message if the issue is with the files.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - NodeJS Version: 8.11.3
 - jscpd version: 5.6.0

**Comment by yoyo837** [comment]
Same here.

**Comment by kucherenko** [comment]
Thank you for the report, will fix it

**Comment by kucherenko** [comment]
fixed at jscpd@2.0.12
