### ISSUE TITLE
Option to set code ignores in config file

### ISSUE THREAD

**Issue by kentmz** [kucherenko/jscpd#215]
Hi,

If want to use jscpd on a very large project, it makes it difficult to decorate every file with jscpd:ignore-start and jscpd:ignore-end and also doesn't make the code look very pretty. If there is a way we could do this in the config file. That way, I can just update at one place. May be the config can have a path to the ignore file, something like "jscpd-ignores": ["codeignores.json"]

Another option can be to provide a flag in the command, like --ignoreImports or --ignoreHeaders or something like that so that it only analyses the methods in case of JS or Typescript or body in case of html.

**Comment by kucherenko** [comment]
thank you for the feature request, will think about the suggestion

**Comment by Larsrdev** [comment]
--ignoreImports would be a great feature. Adding jscpd:ignore-start and jscpd:ignore-end on thousands of files isnt a good way.

**Comment by mitschmidt** [comment]
@Larsrdev I agree - globally ignoring import * statements from clone detection would be very useful in larger projects.
Thanks @kucherenko for this nice tool, we are heavily using it in most of our projects right now.

**Comment by cornr** [comment]
This would be an awesome feature.

**Comment by tholewebgods** [comment]
I've just tested jscpd on a large code base. I'm not convinced that maintaining ignores, be it in-code or as separate config is the way to go. In the former case, it adds clutter to the code, in the ladder case code an config _will_ get out of sync.

In cases where code duplication cannot be avoided defining some rules/patterns to ignore code duplication for would be better maintainable, I think. For example, if multiple modules repeatedly configure something in a certain way, this might not be a duplication that must be avoided. One could specify some pattern in form of an AST-like rule or a JSON object with wildcards to blacklist code.

I might add a separate feature request for that.

**Comment by andergtk** [comment]
@kucherenko  Is there any work being done to implement this feature?

**Comment by mustafaozhan** [comment]
It will be great to have this! Looking forward to it 🙂

**Comment by kucherenko** [comment]
You can use `--ignore-pattern` for ignore some code blocks, added at jscpd@3.4.1
