### ISSUE TITLE
More responsive output

### ISSUE THREAD

**Issue by nonlux** [kucherenko/jscpd#22]
I have less file with:
````
.some-class-1 {
  .mixin();
}


.some-class-2 {
  .mixin();
}
````

My tokens option is 10

Then I run jscpd, I get output:
````
- my.less  1-4
  my.less  5-8

.some-class-1 {
  .mixin();
}
````
it is difficult to understand what code duplicate.

May be split output for not equal tokens:
````
.some-clas...
  .mixin();
}
````

Or use ansi colors for highlighting token ?

**Comment by kucherenko** [comment]
I've made few improvements of output, but I can't highlight tokens for now
