### ISSUE TITLE
Make `memory` the default store

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#231]
**Is your feature request related to a problem? Please describe.**
The default store `level` has few disadvantages over `memory`:
  - it creates an intermediary `.jscpd/` folder.
  - it is slower. At least on one medium-size repository I tried, it took 20 seconds for `level` and 15 seconds for `memory`.

I think the main issue with `memory` is that it does not work with huge repositories. However, the vast majority of users won't have that edge case. The ones that do can opt-in to use `level` instead.

**Describe the solution you'd like**
Change the default value of `storeOptions` to `level` instead.

**Comment by kucherenko** [comment]
I remember your suggestion, I'm thinking about the best strategy to move to the new architecture. Also, I'm going to add a few optimisations of performance.

**Comment by ehmicky** [comment]
I might be missing the implementation details, but actually that would not be about changing the architecture for this issue. But instead just changing the default store method. `memory` is already implemented, so it's just about changing the default value.

**Comment by diegocr** [comment]
Anythihng that improves the performance will be very welcome... i did just upgraded from 0.6.25 to 2.0.15 and running it for JS files over my company [repo](https://github.com/meganz/webclient) takes +15 minutes :face_with_head_bandage:

**Comment by kucherenko** [comment]
Hi there.
I hope you still interesting in the jscpd.
Currently I'm going to release new version of jscpd@3.3.0 and test functionality with jscpd@3.3.0-rc.3.

So, jscpd moved to monorepo with lot of improvements: memory will be is default store. If you want to use other store you can install it (e.g @jscpd/leveldb-store) and use following command:

```
jscpd ./path/to/clones --store leveldb
```

the functionality still in RC, it would be great if you can provide any feedback regarding the functionality, new API and performance. I will release soon to main branch and close the issue.

More info located here - [jscpd monorepo](https://github.com/kucherenko/jscpd/tree/monorepo)

**Comment by diegocr** [comment]
Sounds promising, looking forward to it!

Thanks for the update 👍

**Comment by kucherenko** [comment]
fixed in jscpd@3.3.0-rc.9
