### ISSUE TITLE
UnhandledPromiseRejectionWarning when parsing JS Files

### ISSUE THREAD

**Issue by apaier** [kucherenko/jscpd#234]
**Describe the bug**
I dumped out a large number of JS Files for analysis.  Not sure the specific cause of the problem.  After running for a while the code returns with the error -

(node:8754) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sourceId' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/jscpd/build/clone/index.js:66:55)
    at step (/usr/local/lib/node_modules/jscpd/build/clone/index.js:32:23)
    at Object.next (/usr/local/lib/node_modules/jscpd/build/clone/index.js:13:53)
    at fulfilled (/usr/local/lib/node_modules/jscpd/build/clone/index.js:4:58)
(node:8754) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8754) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
1. Extract the attached js files into a directory
2. npx jscpd ./js 
3. The error occurs

**Expected behavior**
The analysis concludes or a better error is returned to allow for correction of any file problems.

**Desktop (please complete the following information):**
 - OS: MacOs
 - OS Version: 10.14.4
 - NodeJS Version: 6.5.0

[js.zip](https://github.com/kucherenko/jscpd/files/3152842/js.zip)

**Comment by kucherenko** [comment]
Fixed in jscpd@3.1.0
