### ISSUE TITLE
Reporters not consistently reporting the same output

### ISSUE THREAD

**Issue by stoneLeaf** [kucherenko/jscpd#243]
**Describe the bug**
The console and HTML reporters do not consistently report the same output, all the while the verbose reporter does.

**To Reproduce**
Run jscpd twice consecutively on the same repo without any changes to the files nor the jscpd configuration.

**Expected behavior**
JSCPD reports should always be identical when run on the same files with the same configuration.

**Case**
These two commands were run consecutively, without any changes to the files nor the jscpd configuration.
![jscpd_bug_report](https://user-images.githubusercontent.com/770825/58812658-96e34e80-8622-11e9-8fa4-f4b81fe1e288.png)
The HTML reports generated were similar in both cases to the console report, meaning that files missing from the console report were also missing from the HTML report.
When I added the verbose reporter, I could see that even if the console and HTML reports did not reflect it, the 4 files were always scanned.

**Desktop**
 - OS: Windows
 - OS Version: 10
 - NodeJS Version: 10.15.3
 - jscpd version: 2.0.15

**Additional context**
It should be noted that I encountered that behavior on a very small repository comprising of only a few very small files.

**Comment by kucherenko** [comment]
Thank you for the report!

May I ask you to show a result of the execution of the command:
```
jscpd --config .jscpd.json src --debug
```

**Comment by stoneLeaf** [comment]
@kucherenko here's the debug output:

![jscpd_bug_report_2](https://user-images.githubusercontent.com/770825/58875063-d5ccdf00-86ca-11e9-9b56-6de19db12a76.png)

**Comment by kucherenko** [comment]
I guess you should play with `maxLines`, `maxSize`, `minLines` parameters

**Comment by kucherenko** [comment]
But anyway I will add more information about the case

**Comment by stoneLeaf** [comment]
@kucherenko I'm not sure I understand, do you mean, for instance, that it does not analyze files shorter than minLines?

I don't think that's the case here since, as you can see in the original screenshot, I ran twice the same command on the _same_ files, and the console report does not output the same number of files analyzed. And I did not change any of the settings between the two commands.

**Comment by kucherenko** [comment]
Ok, I got it. I will investigate

**Comment by kucherenko** [comment]
Hi, I'm back.
I hope you still interesting in the jscpd.

Currently I'm going to release new version of jscpd@3.3.0 and test functionality with jscpd@3.3.0-rc.3.

So, jscpd moved to monorepo with lot of improvements: the issue fixed here.

the functionality still in RC, it would be great if you can provide any feedback regarding the functionality and the issue. I will release soon to main branch and close the issue.

More info located here - [jscpd monorepo](https://github.com/kucherenko/jscpd/tree/monorepo)

**Comment by kucherenko** [comment]
fixed in jscpd@3.3.0-rc.9
