### ISSUE TITLE
Is jscpd support comparasions between commit diffs and all sources?

### ISSUE THREAD

**Issue by a20185** [kucherenko/jscpd#254]
**Is your feature request related to a problem? Please describe.**
Want to compare the files from diffs in branchs between master and all other source files , like using eslint to compare diffs to increase comparing speed and reduce the report size. Is this feature will be supported?

**Describe the solution you'd like**
Support diff commits in config files or cli

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by kucherenko** [comment]
Thank you for feature request, I will investigate

**Comment by adiroiban** [comment]
Thanks for this nice tool.

Maybe my comment is a different feature request.

I am looking to deploy `jscpd` for an existing 10+ project.
There are already a few copy paste instances.

My main goal is that from now on, at least any new code doesn't contain duplication... and with time, the legacy code will see reduced duplication.

So, besides the normal full report, it would be nice to get a report with 0% threshold for the changes with the main branch.

Slava Ukraini!

**Comment by kucherenko** [comment]
Hi @adiroiban! I appreciate your support of Ukraine. 

You can fix thresholds for old code and control that the level of duplication is not higher than the existing one.

Also, you can use the following bash script for check duplication just in changed files:

```bash
git diff --name-only [sha1 sha2] | xargs jscpd
```

**Comment by kucherenko** [comment]
Btw, I'm going to close the issue due to the existing workaround, you can try to use the following command for that

```bash
git diff master..feature --name-only | xargs jscpd
```

**Comment by adiroiban** [comment]
I think that this can be closed.

I don't understand the original comment.

but having the json reporter helps a lot.

-----------

Updating the threshold is a workaround if you want to update the threshold after each commit to the main branch.

If you have a PR in which a lot of non-duplicate code is removed the duplicate percentage will go up.

Also, if you remove duplicate codes in a PR you might forget to lower the configured threshold... leave spare lines to be duplicated in future PRs :)

--------

The git diff workaround is a start.

It will only detect duplicates inside single file, or between files of that diff.

```
Clone found (python):
 - chevah/server/authentication/ldap.py [24:1 - 35:16] (11 lines, 82 tokens)
   chevah/server/authentication/radius.py [18:1 - 30:16]
```

Run again

```
jscpd chevah/server/authentication/radius.py
Found 0 clones.
```

----------------

But I think I have a way forward to implement this.

Do a full `jscpd` run with json reporter.

Re-use the code from here https://github.com/Bachmann1234/diff_cover/blob/main/diff_cover/diff_reporter.py to get the line number from the diff.

Compare the line ranges from json-reporter with the line ranges from diff.

If there is no match, all good. it means the duplicates are outside of the diff.

**Comment by kucherenko** [comment]
good point, also I can suggest using persistent storage for hashes, in this case, you can increase the speed of detection process in case of a big repository https://www.npmjs.com/package/@jscpd/leveldb-store

**Comment by ensorrow** [comment]
What if I introduced a new duplication of some file beyond the diffs? `git diff --name-only [sha1 sha2] | xargs jscpd` only check the diff files.

**Comment by adiroiban** [comment]
The diff will not work... the diff is just a workaround that might fix some cases.

--------

Another idea.

Instead of the JSON custom report, produce a [JSCover](http://tntim96.github.io/JSCover/) report, in which the duplicate lines are marked as not having coverage.

Then, you can use standard code coverage reporting tools - https://pypi.org/project/diff-cover/

The semanting is a bit different , but the end result should be the same.

The duplicate lines will be reported as missing coverage.

And the nice thing is that by submitting a standard coverage report, you can hack some GitHub  PR inline reporting via standard coverage services like codecov.io
