### ISSUE TITLE
Unknown option --reporter

### ISSUE THREAD

**Issue by andywillis** [kucherenko/jscpd#26]
Installing through npm and running your example in the folder where my files are:

`jscpd --files **/*.js --exclude **/*.min.js --reporter json --output report.json`

gives me the error

> ERROR: Unknown option --reporter

Any ideas why?

**Comment by kucherenko** [comment]
Reporters are not in npm, will add it soon

**Comment by dmi3y** [comment]
@kucherenko what do you think, if we'll create branch or reuse one of the branches for dev purposes and will use master for npm releases only?

**Comment by kucherenko** [comment]
@dmi3y yes, it is good idea, I'm thinking about it

**Comment by kucherenko** [comment]
New version of jscpd already in npm
