### ISSUE TITLE
Ignored Blocks comments doesn't ignore markup

### ISSUE THREAD

**Issue by 06b** [kucherenko/jscpd#274]
**Describe the bug**
Adding Ignored Blocks comments to markup doesn't appear to be ignored.

**To Reproduce**
1. Have duplicated markup which jscpd finds as a clone.
2. Wrap the markup with `<!--jscpd:ignore-start-->`  & `<!--jscpd:ignore-end-->`
3. Run jscpd

**Expected behavior**
jscpd should ignore the markup.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Version: 1903
 - NodeJS Version: 10.16.3
 - jscpd Version: 2.0.16

**Comment by kucherenko** [comment]
Thank you for the issue, will investigate it

**Comment by josephzidell** [comment]
@kucherenko were you able to find any info? We're running into this issue as well. This is one of the best copy-paste detector tools for JS out there, and I'm hoping we can gain clarity on this.

**Comment by kucherenko** [comment]
Hi

Please use following comments for mark ignored blocks:

```
<!--
// jscpd:ignore-start
-->
... ignored block here ...
<!--
// jscpd:ignore-end
-->
```

**Comment by kucherenko** [comment]
Updated README and close the issue
