### ISSUE TITLE
Usage of command-line flags in .cpd.yaml file?

### ISSUE THREAD

**Issue by b-long** [kucherenko/jscpd#28]
Hi, great project!

Is it possible to use the command-line flags (e.g. `--min-tokens` as `minTokens` in the YML file) ?

**Comment by kucherenko** [comment]
yes, you can use jscpd with --min-tokens or with -t

 -l, --min-lines [NUMBER]min size of duplication in code lines (Default is 5)
  -t, --min-tokens [NUMBER]mim size of duplication in code tokens (Default is 70)

**Comment by b-long** [comment]
@kucherenko Sorry, can we re-open this.  What I mean to ask is, how do we use those flags inside the YML file?

**Comment by paulintrognon** [comment]
Have you found the answer @b-long ? I want to do the same :)

**Comment by b-long** [comment]
I haven't @paulintrognon , sorry to say.

**Comment by kucherenko** [comment]
sorry for late answers, I will fix this issue

**Comment by kucherenko** [comment]
done

**Comment by kucherenko** [comment]
you can use  `min-tokens` and `min-lines` inside yaml file

**Comment by b-long** [comment]
Excellent!  Thanks @kucherenko :)
