### ISSUE TITLE
JSX files

### ISSUE THREAD

**Issue by golmansax** [kucherenko/jscpd#29]
We are using jscpd for JS files, is there a way to get it to work with React's JSX files as well?

**Comment by kucherenko** [comment]
I got it, will do it at next version

sorry for late answer

**Comment by golmansax** [comment]
no worries, thanks!

**Comment by kucherenko** [comment]
Done with jsx

**Comment by golmansax** [comment]
awesome :+1:

**Comment by danii1** [comment]
I came here to say that this tool is awesome and author is awesome, thank you!
