### ISSUE TITLE
Offline report 

### ISSUE THREAD

**Issue by bendanye** [kucherenko/jscpd#319]
**Is your feature request related to a problem? Please describe.**
Able to generate local version of jscpd html report without the need of internet access. Currently the html report scripts' src is pointing to outside CDN which on-premise CICD may not have connection to outside world. 

**Describe the solution you'd like**
A way for the html report scripts' src point to local environment with additional cli option like --offline

**Comment by kucherenko** [comment]
thank you for the feature request

**Comment by kucherenko** [comment]
Added new html reporter, all resources saved locally
jscpd@3.3.16

**Comment by kucherenko** [comment]
Added new html reporter, all resources saved locally
jscpd@3.3.16
