### ISSUE TITLE
Only compare across two dirs (code bases)

### ISSUE THREAD

**Issue by appelflap** [kucherenko/jscpd#326]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more a feature request. Will fix amount of output though. And add ease of use for this specific use case. At the moment I make a dir and add two symlinks to that dir to compare two code bases. Problem is that 95% of the output needs to be filtered out (duplicates within one code base).

**Describe the solution you'd like**
Being able to point to two separate dirs and only output clones that match across those dirs. Not the clones within one dir.

**Describe alternatives you've considered**
Parsing the html/json output removing all duplicates where the basedir match. But JSON is easy to parse, but HTML output is very nice and no way to go from filtered JSON to HTML output.

**Comment by kucherenko** [comment]
Thank you for the feature request, it is excellent idea

**Comment by kucherenko** [comment]
implemented in jscpd@3.2.0
