### ISSUE TITLE
--formats-exts value format

### ISSUE THREAD

**Issue by ijandc** [kucherenko/jscpd#329]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34884325/75736217-90ac0b00-5d37-11ea-9c07-0724f25b24f6.png)
**To Reproduce**
exec the command:
```
 sudo jscpd -o /Users/jcmac/TC/codecheck/report111 --formats-exts css:wxss;markup:wxml test5 --absolute true
```
will get the error:

```
zsh: command not found: markup:wxml
```
**Expected behavior**
no error

**Screenshots**
![image](https://user-images.githubusercontent.com/34884325/75736217-90ac0b00-5d37-11ea-9c07-0724f25b24f6.png)

**Desktop (please complete the following information):**
 - OS: [macOS ]
 - OS Version [10.14.6]
 - NodeJS Version [11.0.0]
 - jscpd version [2.0.16]

**Additional context**
nothing

**Comment by Charon1997** [comment]
Hello, I also encountered the same problem, how did you solve it?
