### ISSUE TITLE
How do I detect code that are not completely same but structrally same?

### ISSUE THREAD

**Issue by itamud** [kucherenko/jscpd#330]
Is it already supported or planned?
I've read all the readme but didn't find any option about detecting structurally same code.Any help would be grateful.

**Comment by kucherenko** [comment]
Hello
Currently it is not supported from the box. jscpd use Rabin-Karp algorithm for duplicates detection and don't use source tree as input for detection. You can try to find other tools for you task, for example jsinspect.
