### ISSUE TITLE
Is 3.0.0 an official release?

### ISSUE THREAD

**Issue by screendriver** [kucherenko/jscpd#332]
I saw that `v3.0.0` [was released](https://www.npmjs.com/package/jscpd) but didn't find any release or related commits here on this repository. So is this an official release or did someone stole your npm credentials or something like that? 🤔

**Comment by kucherenko** [comment]
Hello, 
v3.0.0 is official release

Version 3.0.0 contains fixes for bugs and I expect to start new functionality with 3.x branch of versions.

Thank you for following jscpd and sorry for little bit unclear versioning

**Comment by screendriver** [comment]
Thank you for clarification 👍
