### ISSUE TITLE
Anyway to ignore import statements of a file to be considered as duplicated code?

### ISSUE THREAD

**Issue by sai789** [kucherenko/jscpd#341]
Hi everyone,
I'm facing a problem where jscpd is considering set of import statements that are duplicated among two files.
ex: referral.ts - file one
-----------------------
import {FhirClient} from '../fhir/fhir-client';
import {map} from 'lodash';
import * as fs from 'fs';
import {promisify} from 'bluebird';
import * as path from 'path';
import {logger} from '../logger';

export class Referral {
// some code here
}

authorization.ts - file two
-------------------------
import {FhirClient} from '../fhir/fhir-client';
import {map} from 'lodash';
import * as fs from 'fs';
import {promisify} from 'bluebird';
import * as path from 'path';
import {logger} from '../logger';

export class Authorization {
// some code here
}

jscpd is considering import statements in both files are duplicated, and so validation fails.

Please suggest how to solve this problem? - of course I don't want to use these `// jscpd:ignore-start` and `// jscpd:ignore-end`  which means if I choose this, I would have to use these comments everywhere whenever I see this problem.

I'm not sure if jscpd is already supporting some flag to ignore imports of a file. If so please let me know here, if not can't we consider this as a feature request?

Thanks

**Comment by kucherenko** [comment]
Currently it is not supported. jscpd supports over 150 languages and it is easy to achieve "smart" ignore blocks.

**Comment by VirajShah21** [comment]
How do you accomplish this?

**Comment by mmansoor** [comment]
From documentation : https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#ignored-blocks

Mark blocks in code as ignored:
```javascript
/* jscpd:ignore-start */
import lodash from 'lodash';
import React from 'react';
import {User} from './models';
import {UserService} from './services';
/* jscpd:ignore-end */
```

```html
<!--
// jscpd:ignore-start
-->
<meta data-react-helmet="true" name="theme-color" content="#cb3837"/>
<link data-react-helmet="true" rel="stylesheet" href="https://static.npmjs.com/103af5b8a2b3c971cba419755f3a67bc.css"/>
<link data-react-helmet="true" rel="stylesheet" href="https://static.npmjs.com/cms/flatpages.css"/>
<link data-react-helmet="true" rel="apple-touch-icon" sizes="120x120" href="https://static.npmjs.com/58a19602036db1daee0d7863c94673a4.png"/>
<link data-react-helmet="true" rel="apple-touch-icon" sizes="144x144" href="https://static.npmjs.com/7a7ffabbd910fc60161bc04f2cee4160.png"/>
<link data-react-helmet="true" rel="apple-touch-icon" sizes="152x152" href="https://static.npmjs.com/34110fd7686e2c90a487ca98e7336e99.png"/>
<link data-react-helmet="true" rel="apple-touch-icon" sizes="180x180" href="https://static.npmjs.com/3dc95981de4241b35cd55fe126ab6b2c.png"/>
<link data-react-helmet="true" rel="icon" type="image/png" href="https://static.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png" sizes="32x32"/>
<!--
// jscpd:ignore-end
-->
```
