### ISSUE TITLE
Not working on Windows systems

### ISSUE THREAD

**Issue by Wandaymo** [kucherenko/jscpd#345]
**Describe the bug**
When I trying to run the jscpd an erro occurs

**To Reproduce**
Run the jscpd on Windows 10

**Expected behavior**
Error to read path

**Screenshots**

![image](https://user-images.githubusercontent.com/11556295/79241263-35e2f480-7e49-11ea-8eb7-d57447c84944.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS Version [10]
 - NodeJS Version [8.15.0]
 - jscpd version [3.2.0]

**Additional context**

**Comment by kucherenko** [comment]
Thank you for the report, looks like the issue with version of node.js, not with Windows OS

**Comment by jazzzz** [comment]
> Thank you for the report, looks like the issue with version of node.js, not with Windows OS

Yes, it does not work on Node 8, see #346.

**Comment by kucherenko** [comment]
fixed at jscpd@3.2.1
