### ISSUE TITLE
Jscpd counts fewer lines of code than other tools, eg cloc

### ISSUE THREAD

**Issue by raxliao** [kucherenko/jscpd#371]
OS: MacOs

Same Directory
The result from jscpd
![image](https://user-images.githubusercontent.com/8636891/87037179-68b94080-c21e-11ea-96ea-1d986849d280.png)

The result from cloc 
![image](https://user-images.githubusercontent.com/8636891/87037299-93a39480-c21e-11ea-9824-fcdcdbacab81.png)

**Comment by kucherenko** [comment]
The jscpd tool skip huge files. You can play with parameters:

-x, --max-lines [number]   max size of source in lines (Default is 500)
-z, --max-size [string]    max size of source in bytes, examples: 1kb, 1mb, 120kb (Default is 30kb)

**Comment by raxliao** [comment]
Sorry ，that is my fault.  The thrift gen files is too large to skiped by jscpd。by the way , dose jscpd skip blank lines？ 
It seems not。
