### ISSUE TITLE
XML file: escape file name with special character

### ISSUE THREAD

**Issue by juli1** [kucherenko/jscpd#376]
**Describe the bug**

If a file has a special character for the XML format, this is not escaped and created a parsing error.

**Example**
if the file contains the `&` symbol, the generated XML will be like

```
<file path="blabla/foo & bar.json" line="67">
</file>
```

I believe that such characters should be encoded, such as [mentioned here
](https://webfocusinfocenter.informationbuilders.com/wfappent/TL2s/TL_lang/source/xmlencod.htm)

**To Reproduce**

 1. Run JSCPD on a codebase with file having the `&` symbol
 2. Export the results as XML file
 3. Use xmllint to check the file

**Expected behavior**

The generated XML file should be parsed.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - NodeJS Version 10
 - jscpd version 3.3.0

**Comment by kucherenko** [comment]
fixed at jscpd@3.3.1
