### ISSUE TITLE
Allow programmatic usage

### ISSUE THREAD

**Issue by lo1tuma** [kucherenko/jscpd#38]
Hi,

I would like to use `jscpd` programmatically where I can provide the file content instead of letting `jscpd` reading the file from the file-system.

Background of this is, that I want to check files retrieved via the github API.

---

The API could look like this:

``` js
var Detector = require('jscpd').Detector;

var detector = new Detector();

detector.addFile('foo.js', 'console.log("hello world")');
detector.addFile('bar.js', 'console.log("hello world")');

var result = detector.run();
```

**Comment by kucherenko** [comment]
for now you can use program interface, but it is little bit poor, will add this request to plans

**Comment by c089** [comment]
The second argument in the `addFile` method be the contents of the file, right? Then maybe rename it to something more generic to make it clear this is not reading a file, but expecting a string? Otherwise :+1:

**Comment by lo1tuma** [comment]
It would be also nice to be able to remove files, so you can compare the duplication results of two different versions of your code files.

Example:

```js
var Detector = require('jscpd').Detector;

var detector = new Detector();

// add files of version 1
detector.addFile('foo.js', 'console.log("hello world")');
detector.addFile('bar.js', 'console.log("hello world")');
detector.addFile('baz.js', 'console.log("hello world")');

var resultOfVersion1 = detector.run();

// apply changes to get to version 2
detector.addFile('bar.js', 'console.log("changed file")');
detector.removeFile('baz.js');

var resultOfVersion2 = detector.run();

console.log('Your code duplication increased/decreased by:', compareResults(resultOfVersion1, resultOfVersion2, 'percent');
```

**Comment by kucherenko** [comment]
https://github.com/kucherenko/jscpd/blob/master/docs/api.md

New version of jscpd released and powerful API there
