### ISSUE TITLE
Add a `CHANGELOG` entry for `3.3.1`

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#382]
I have been using `3.2.1` and upgrading to `3.3.1` seems to be breaking due to removing the `JSCPD` constructor:

```js
TypeError: _jscpd.JSCPD is not a constructor
  at Object.<anonymous> (/home/ether/code/get-sourcemaps/node_modules/@ehmicky/dev-tasks/build/src/tasks/check/jscpd.js:23:21)
```

It is hard to get a grasp of the new features and APIs introduced by `3.3.*` since the changelog shows [that 701 files have changed](https://github.com/kucherenko/jscpd/compare/v3.2.1...v3.3.1).

Would it be possible to write an entry in the `CHANGELOG` with a detailed list of the changes? Thanks a lot!

**Comment by kucherenko** [comment]
Thank you for the issue.

Starting from 3.3.x jscpd moved to monorepo and change API.

You can check documentation here - https://github.com/kucherenko/jscpd, https://github.com/kucherenko/jscpd/tree/master/packages/jscpd and here https://github.com/kucherenko/jscpd/tree/master/packages/core. 

Also you can check examples folder.

Looks like changelog generator was broken while I migrate to monorepo, I'll fix it.

**Comment by kucherenko** [comment]
Feel free to ask me about new API here in the thread.

**Comment by ehmicky** [comment]
Hi @kucherenko,

Thanks for your response.
This is a rather big change, is there a migration guide? Also, is there a list of changes available between those two versions?

**Comment by ehmicky** [comment]
I have gone through the source code of the new modules, and I am now aware of the changes introduced in `3.3.1`. Please feel free to close this issue, unless you want to keep it open to update with the progress of it. Thanks!

**Comment by kucherenko** [comment]
I will close it after I will fix changelog generator and add more information about API usage.
