### ISSUE TITLE
Missing SRI (integrity attribute) for scripts & links in html report

### ISSUE THREAD

**Issue by emanuelb** [kucherenko/jscpd#384]
From:

https://github.com/kucherenko/jscpd/blob/633a854335dc1c82c9d64ea44c04533ccdd55693/packages/finder/html/layout.pug#L8-L12
only the first link and last script have integrity attribute.

fix:
add integrity attribute for all scripts/links used from cdnjs.cloudflare.com that use fixed versions (as above links does)

**Comment by kucherenko** [comment]
Will be fixed with https://github.com/kucherenko/jscpd/issues/319

**Comment by kucherenko** [comment]
Added new html reporter, all resources saved locally
jscpd@3.3.16
