### ISSUE TITLE
Add option to opt-out of GoogleTagManager in html report

### ISSUE THREAD

**Issue by emanuelb** [kucherenko/jscpd#385]
**Describe the bug**
From:
https://github.com/kucherenko/jscpd/blob/080fe480c55adb8cab77b7c5191c1c11d647112e/packages/finder/html/layout.pug#L342-L349

The generated html report will contain script that load googletagmanager script.

**Expected behaviour**

This script is not inserted by default or at least there is a option to disable it, for example you can check the value of `DO_NOT_TRACK=1` environment variable value, see: https://consoledonottrack.com/
and mention in documentation that it can be used to disable this script/analytics/tracking.

**Comment by kucherenko** [comment]
fixed at jscpd@3.3.2
