### ISSUE TITLE
Add an option that makes CLI exit code non-`0` when some clones are detected

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#387]
I am using `jscpd` as part of my CI. If any clones is detected, I would like my CI to fail.

This is not easily doable through the CLI (without using the `stdout`, which feels brittle), which means I have to use the programmatic `@jscpd/core`, which is not as simple.

An option that makes the CLI exit code non-`0` when any clone is detected could help fix. What do you think?

**Comment by kucherenko** [comment]
I can suggest to use `--threshold` parameter for `jscpd` CLI for that, but if you are going to have non zero exit code with `@jscpd/core` you should write a code for that. 
Also I can suggest use jscpd function from jscpd package like here:

```typescript
import {IClone} from '@jscpd/core';
import {jscpd} from 'jscpd';


const clones: Promise<IClone[]> = jscpd(process.argv);
// or
(async () => {
  try {  
      const clones: IClone[] = await jscpd(['', '', '/path/to/file/or/folder', '-m', 'weak', '--silent']);
  } catch (e) {
   // in case of clones level more than threshold exception will be here
  }
})();
```
But anyway in case of API usage for detection user should add logic of exit manually.

**Comment by ehmicky** [comment]
Hi @kucherenko,

Thanks, the `--threshold` flag works perfectly for my case!
