### ISSUE TITLE
Allow using globbing in CLI

### ISSUE THREAD

**Issue by ehmicky** [kucherenko/jscpd#388]
The CLI might not be running in a shell, which is especially common in CI. Using shells has many [drawbacks](https://github.com/sindresorhus/execa#shell) which some users (like me) might want to avoid.

For this reason, it would be nice for the `jscpd` CLI to provide an option to expand globbing patterns (or do it by default). At the moment, the only globbing that is performed is: when a directory is specified, `**/*` is appended. Some users might have more advanced globbing patterns.

Another advantage is this would allow overcome the maximum length of commands. For example, I tried expanding the globbing myself and passing each file as argument to `jscpd` CLI, but the GitHub action CI on Windows failed due to the list of arguments being bigger than the allowed limit.

What do you think?

**Comment by kucherenko** [comment]
Good point, will add the customization of glob pattern.

Also I can suggest to use .jscpd.json for describe files to detect, more info here - https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#config-file

**Comment by kucherenko** [comment]
With jscpd@3.3.9 you can use following command:

```sh
jscpd --pattern "**/*.ts"
```
