### ISSUE TITLE
Add build instructions from git clone

### ISSUE THREAD

**Issue by emanuelb** [kucherenko/jscpd#390]
There missing instructions for building this project from:
`git clone --depth 1 https://github.com/kucherenko/jscpd/`
what steps are needed?
in order to be able to run `./jscpd`
see the issue https://github.com/kucherenko/jscpd/issues/356#issue-615406334
which I added containerfile that use `npm install` in comment, but it's better to have containerfile that use 'COPY' instruction (to run the cloned/development version).

**Comment by kucherenko** [comment]
You can find https://github.com/kucherenko/jscpd#start-contribution guide for start development

**Comment by emanuelb** [comment]
Thanks, somehow missed it, maybe add a line that then jscpd will then be run from `./packages/jscpd/bin/jscpd`? added Containerfile that use COPY in comment here https://github.com/kucherenko/jscpd/issues/356#issuecomment-671394772
