### ISSUE TITLE
Install project dependency error

### ISSUE THREAD

**Issue by fyangstudio** [kucherenko/jscpd#391]
**Describe the bug**
package.json
```json
{
  "name": "xxx",
  "version": "0.1.0",
  "dependencies": {
    "jscpd": "^3.3.1"
  }
}
```
run yarn
show the error:
![image](https://user-images.githubusercontent.com/9896768/89750626-583b0500-daff-11ea-803f-888eb9b31919.png)

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS Version [e.g. 22] ,macOS 10.15.6 
 - NodeJS Version [e.g. 9, 10, 11] v10.15.3
 - jscpd version 3.3.1

**Comment by kucherenko** [comment]
Thank you for the report, will fix the issue soon

**Comment by kucherenko** [comment]
I trying to reproduce the issue and can't do it. 

I use node with same version - v10.15.3, I use yarn version 1.22.4. 

```sh
$> yarn config get registry
https://registry.yarnpkg.com
``` 

I run following command with following result:

```sh
yarn
yarn install v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning jscpd > @jscpd/finder > pug > pug-filters > constantinople > babel-types > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 4.23s.
```

**Comment by kucherenko** [comment]
Could you please provide more information about the issue?

**Comment by fyangstudio** [comment]
thx, maybe there some thing wrong with yarn cache
