### ISSUE TITLE
Upgrade components in HTML report

### ISSUE THREAD

**Issue by emanuelb** [kucherenko/jscpd#392]
The component versions is old:

https://github.com/kucherenko/jscpd/blob/8c01a1cc188780847a2cbbc2d0adea21ca1a6f46/packages/finder/html/layout.pug#L8-L12

purecss - used 1.0.0, latest is: 2.0.3 , see:
https://unpkg.com/browse/purecss@2.0.3/

prism - used 1.15.0 , latest is: 1.21.0 , see:
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/prism/

echarts - used 4.1.0 , latest is: 4.8.0, see:
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/echarts/

related issue: #384 (to apply integrity attribute)

**Comment by kucherenko** [comment]
I'm going to rewrite html reporter and remove all links to cdn, the issue will be fixed after new html reporter relese.

**Comment by kucherenko** [comment]
Added new html reporter, all resources saved locally
jscpd@3.3.16
