### ISSUE TITLE
API error in typescript project: Type 'typeof EventEmitter' is not a constructor function type

### ISSUE THREAD

**Issue by fyangstudio** [kucherenko/jscpd#400]
**Describe the bug**

![image](https://user-images.githubusercontent.com/9896768/93043065-4d860980-f683-11ea-89ed-9e11636dc13a.png)

**To Reproduce**
Use in typescript project.
 tsc -p ./

```
// tsconfig
{
  "compilerOptions": {
    "outDir": "build",
    "rootDir": "src",
    "noImplicitAny": false,
    "module": "commonjs",
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "include": ["src", "schema"],
  "exclude": ["node_modules", "web"]
}

```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - OS Version [e.g. 22] 10.15.6
 - NodeJS Version [e.g. 9, 10, 11] 10.15.3
 - jscpd version [e.g. 0.6.x, 1.0.x, 2.0.3] 3.3.17

**Additional context**

**Comment by kucherenko** [comment]
thank you, will take a look

**Comment by fyangstudio** [comment]
Quick fix this problem is to skip the check in my project tsconfig.json :
```
 "compilerOptions": {
    "skipLibCheck": true
  },
```

Maybe i can ignore this issue
