### ISSUE TITLE
warning: time not installed (install packages named @jscpd/time-reporter or jscpd-time-reporter)

### ISSUE THREAD

**Issue by quoininc-huudatran** [kucherenko/jscpd#401]
**Describe the bug**

There is a new warning displayed and neither packages are available:

```
warning: time not installed (install packages named @jscpd/time-reporter or jscpd-time-reporter)
Cannot find module '@jscpd/time-reporter'
```

**To Reproduce**
1. I just run `jscpd src`

**Expected behavior**
Either remove the warning, or publish the package.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version 10.15.6
 - NodeJS Version v12.18.3
 - jscpd version 3.3.19

**Additional context**

**Comment by kucherenko** [comment]
Thank you for the report, will investigate the issue

**Comment by quoininc-huudatran** [comment]
bump
