### ISSUE TITLE
getTokensCount() returns number of characters, not number of tokens.

### ISSUE THREAD

**Issue by lolgab** [kucherenko/jscpd#405]
Trying to implement the token count for the clones I found that the token count returned by `getTokensCount()` is not the token count but the total number of chars between first and last token. Since tokens have a length this sounds wrong to me.
What do you think?

**Comment by kucherenko** [comment]
In the method you can find following code:

```typescript
public getTokensCount(): number {
    return this.tokens[this.tokens.length - 1].loc.end.position - this.tokens[0].loc.start.position;
}
```

`position`  is a property with index of token in array of tokens, you can investigate `calculateLocation` method
