### ISSUE TITLE
Can't ignore 'build/index.ffd156e179b43c81e3d7.hot-update.js' file

### ISSUE THREAD

**Issue by fyangstudio** [kucherenko/jscpd#419]
**Describe the bug**
Set ignore 'build/**' but can't ignore 'build/index.ffd156e179b43c81e3d7.hot-update.js'

**To Reproduce**
```
jscpd --ignore "build/**,build/**.js" /path/to/files
```
The result shows 'build/index.ffd156e179b43c81e3d7.hot-update.js'

**Expected behavior**
Don't show  'build/index.ffd156e179b43c81e3d7.hot-update.js', ignore it.

**Screenshots**
![image](https://user-images.githubusercontent.com/9896768/102738829-3ba0ba80-4386-11eb-9cc5-8702a49306d2.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.7
 - NodeJS Version v10.15.3
 - jscpd version 3.3.22

Looking forward to your reply

**Comment by kucherenko** [comment]
The issue related to fast-glob package, please check the rules in the following link - https://www.npmjs.com/package/fast-glob
