### ISSUE TITLE
cofeescript is required but not listed in package.json

### ISSUE THREAD

**Issue by ghusse** [kucherenko/jscpd#42]
My build is failing because of the latest version of CPD, which seems to require coffee-script, even if this package is not listed in the dependencies of jscpd.

**Comment by kucherenko** [comment]
thank you for report

temperary you can start your build with previous version 0.4.x

**Comment by ghusse** [comment]
Same thing with v0.4.3, it works in 0.4.2

**Comment by kucherenko** [comment]
okey, fixing

**Comment by kucherenko** [comment]
fixed  in 0.5.1
