### ISSUE TITLE
How to inject reportersOptions?

### ISSUE THREAD

**Issue by hata6502** [kucherenko/jscpd#424]
Hello!

I want to inject `reportersOptions` for customized html-reporter in my fork. 
Is there any way to inject reportersOptions?

I use `.jscpd.json` to inject reportersOptions for now. 
Is this a correct way?

```
{
  "reportersOptions": {
    "test": "test"
  }
}
```

thank you for maintaining jscpd.

**Comment by kucherenko** [comment]
Hi!
You can get all current options in constructor of a reporter.
Please take a look the following code of initialisation of typical reporter:
```typescript
        detector.registerReporter(new reporterClass(options)); 
```
