### ISSUE TITLE
Is jscpd support comparasions between different repos?

### ISSUE THREAD

**Issue by NieZhuZhu** [kucherenko/jscpd#428]
**Is your feature request related to a problem? Please describe.**
Checking the duplication between code repositories is like checking duplicates in a paper

**Describe the solution you'd like**
Ability to obtain information about code duplication between different repositories

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by kucherenko** [comment]
For detect duplicates in different repost you can clone a repos to different places and use following command:
```
jscpd --skipLocal /path/to/first/repo /path/to/second/repo
```
More info here - https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#skip-local
