### ISSUE TITLE
150 formats 404 

### ISSUE THREAD

**Issue by NieZhuZhu** [kucherenko/jscpd#429]
**Describe the bug**
150 formats 404: https://github.com/kucherenko/jscpd/blob/master/packages/jscpd/docs/supported_formats.md

**To Reproduce**
1. Go to 'https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#skip-local'
2. Click on '`150 formats`'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/44939961/110415738-5ce38e00-80cd-11eb-9897-1fc85bb9c2ec.png)
![image](https://user-images.githubusercontent.com/44939961/110415929-c9f72380-80cd-11eb-809e-6b1f64574ce4.png)

**Comment by Kurt-von-Laven** [comment]
I noticed this as well. As a workaround, I noticed [this file](https://github.com/kucherenko/jscpd/blob/master/packages/tokenizer/src/formats.ts) appears to list the file formats.
