### ISSUE TITLE
Xunit output

### ISSUE THREAD

**Issue by jazzzz** [kucherenko/jscpd#43]
It would be great for Jenkins.

**Comment by kucherenko** [comment]
what do you mean? could you please show example?

**Comment by jazzzz** [comment]
It's an XML format used by many unit test frameworks. With a [Jenkins plugin][1], it's possible to report the number of failing tests, for jscpd it would be the number of duplicated chunks. You can see a doc and some examples [here][2].

[1]: https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin
[2]: http://reflex.gforge.inria.fr/xunit.html#xunitReport

**Comment by kucherenko** [comment]
You can use this https://wiki.jenkins-ci.org/display/JENKINS/DRY+Plugin plugin with Jenkins and existing XML report from jscpd. Xunit report has different aims and not compatible with jscpd.

**Comment by jazzzz** [comment]
Ho great! Thanks.

**Comment by fairul82** [comment]
I did try on jenkins using DRY ( CPD) ..but doesnt look compatible. any idea how to go about?

**Comment by kucherenko** [comment]
Thank you for issue

I'll check

May I ask you give me more details about this? Any logs, errors?

**Comment by fairul82** [comment]
Thanks .

Here you go ...

[DRY] Parsing of file  report.xml failed due to an exception:
java.io.IOException: No parser found for duplicated code results file report.xml
	at hudson.plugins.dry.parser.DuplicationParserRegistry.parse(DuplicationParserRegistry.java:101)
