### ISSUE TITLE
Need an option to exclude a pattern from code duplication calculation

### ISSUE THREAD

**Issue by rkjaiswal1** [kucherenko/jscpd#435]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There are situations where particular piece needs to be re-used in many files. For exx import statements in java. Need an option to pass file with those contents to be excluded from code duplication calculation and reporting.

Like jscpd --exclude file1.txt.
content of file1.txt can be 

/*import 1
impor2
import 3
impor4
*/

**Describe alternatives you've considered**

**Additional context**

**Comment by kucherenko** [comment]
Thank you for the request, it is looks interesting, will add the feature

**Comment by hata6502** [comment]
`ignore` command will helps you with no jscpd enhancements!

https://github.com/hata6502/ignore-files

Example:

```
jscpd -g $(zsh -c "echo **/*" | ignore .jscpdignore)
```

`.jscpdignore`
```
example
node_modules
```

**Comment by kucherenko** [comment]
@hata6502  the idea here is have some files or blocks of code with content what will be excluded from detection, not just based on filename but on content, I think it can be interesting

**Comment by hata6502** [comment]
Oh, Sorry!
this issue focuses an option to exclude a "pattern", OK.

**Comment by pustovitDmytro** [comment]
would be nice to have a regexp pattern here, for example, js solution could be:

```json
    "ignore": ["**/lib/constants/*.json"],
    "ignorePattern": ["import .* from '.*';"]
```

**Comment by gustawdaniel-acaisoft** [comment]
My solution

```
jscpd `git ls-files`
```

**Comment by Confetti7** [comment]
Is this feature supported? I configured it and it didn't seem to work.
`'ignore-pattern': 'import.*'`

**Comment by kucherenko** [comment]
@Confetti7 ignore-pattern used for excluding from detection files, not contect

**Comment by Davste93** [comment]
> @Confetti7 ignore-pattern used for excluding from detection files, not contect

@kucherenko 
https://github.com/kucherenko/jscpd/blob/b53ce7d8b63ffc0e499ec62ef2d7e071cda8d530/packages/jscpd/README.md?plain=1#L281

Is this answer still valid? Your docs say the opposite of what your comment says, including an example with imports

**Comment by Sam-Lin-MillersLab** [comment]
> Is this feature supported? I configured it and it didn't seem to work. `'ignore-pattern': 'import.*'`

have you tried `ignorePattern` ?

https://github.com/kucherenko/jscpd/commit/98f2f9ebfba3029cef68bbcc66c0061195dfa47a#diff-c003b55fe20d9245425c86b1dd2f0fc239186a25fe1dadd40a8324b772833224
