### ISSUE TITLE
silent was not really silent 

### ISSUE THREAD

**Issue by rhinonan** [kucherenko/jscpd#457]
**Describe the bug**
Use the CLI API detectClones，set options.slient: true, bug still output something.

**To Reproduce**
```js
import { detectClones } from 'jscpd';
console.log(1)
await detectClones({
        path: files,
        silent: true
 });
console.log(2)
```

**Expected behavior**
output:
1
2

**Actually**
output:
1
Found 5 clones.
Detection time: 278.774ms
2

**Desktop (please complete the following information):**
 - OS: [windows]
 - OS Version [10]
 - NodeJS Version [10]
 - jscpd version [3.3.25]

**Additional context**
It is a feature ?

**Comment by kucherenko** [comment]
Fixed at jscpd@3.3.26
