### ISSUE TITLE
Consider a JUnit Reporter

### ISSUE THREAD

**Issue by Kurt-von-Laven** [kucherenko/jscpd#465]
**Is your feature request related to a problem? Please describe.**
Many CI systems offer first-class support for summarizing or displaying test reports provided they are in [the JUnit format](https://www.ibm.com/docs/en/developer-for-zos/9.1.1?topic=formats-junit-xml-format) (or another standard format). The existing XML reporter outputs a custom XML format that other tools do not support.

**Describe the solution you'd like**
Change the XML reporter output format to output in the JUnit format.

**Describe alternatives you've considered**
Keep the XML reporter as-is for backwards compatibility, but introduce a new JUnit reporter. I have little context on how many projects depend on the format of the existing XML reports.

**Additional context**
See [CircleCI's built-in support for displaying test reports](https://circleci.com/docs/2.0/collect-test-data/) or [this GitHub Action](https://github.com/marketplace/actions/publish-unit-test-results) for examples of tools that would be able to leverage this reporter, and boost jscpd's visibility on projects that use it.

**Comment by kucherenko** [comment]
Hi Kurt, as I understand JUnit is for unit testing report, but here we don't have test suites or test cases, that is why I'm not sure that we can use it for copy/paste report? Do you have any examples how we can use it for duplications?

**Comment by Kurt-von-Laven** [comment]
I was envisioning one test suite (e.g., "duplication", "copy/paste detection") with one test case per file checked that succeeds if there were no duplicates and maybe reports the number of clones detected (or possibly the full source of all the clones) as a test failure otherwise?

**Comment by kucherenko** [comment]
I'm sorry, I didn't find good solution for the request, that is why I'm going to close it
