### ISSUE TITLE
Support for multiple patterns

### ISSUE THREAD

**Issue by mig82** [kucherenko/jscpd#467]
**Is your feature request related to a problem? Please describe.**
I have a large codebase with source code in different subdirectories, all with different patterns.

**Describe the solution you'd like**
I'd like to be able to pass multiple patterns to the `--pattern` flag.

**Describe alternatives you've considered**
I'm currently just running it once per pattern, but I could be missing duplicates across these sub-folders.

**Additional context**
I think it would make sense. I've seen in the docs that the `--ignore` flag already supports `,` as a separator for multiple patterns.

**Comment by kucherenko** [comment]
Thank you for the report, I suggest use rules of fast-glob for combining patterns

https://www.npmjs.com/package/fast-glob

**Comment by mikedidomizio** [comment]
For anyone that comes into this, you can use multiple pattern args.

`jscpd --pattern /path/to/files/** --pattern /path/to/otherFiles/**`

or

`jscpd /path/to/files/** /path/to/otherFiles/**`
