### ISSUE TITLE
Ability to support more than two clones per file, or across files? 

### ISSUE THREAD

**Issue by strtw** [kucherenko/jscpd#474]
After running the tool on a file which had three copied blocks of code, the report only shows details about two of the clones. I also noticed in the main image on the README.MD only two matches are indicated. Is it possible to output a report which shows all the locations that a duplicated block of code exists? 

![image](https://user-images.githubusercontent.com/11788126/122844861-662ceb00-d2b7-11eb-8d9b-804336a84b84.png)

**Comment by kucherenko** [comment]
Hi @strtw, thank you for the report, as you can see the issue already reported, I'm going to close this one as duplicate

**Comment by kucherenko** [comment]
Duplicated #221
