### ISSUE TITLE
Feature Request: Add reporter for continuous integration tests

### ISSUE THREAD

**Issue by camsjams** [kucherenko/jscpd#48]
Basically, it would be great to have jscpd optionally exit with a non-zero exit code, in order to use this in a continuous integration environment.

I made a gist that works with your current version of the library, and basically checks some arbitrary threshold and then exits the process with a non-zero exit code:
https://gist.github.com/camsjams/7e3106f710bea5824dbf

Feel free to adapt into the codebase if you agree.

**Comment by kucherenko** [comment]
added limit parameter, you can use it in console or in .cpd.yml file

**Comment by camsjams** [comment]
Excellent! Thanks so much @kucherenko

**Comment by diegokogan** [comment]
How can we prevent to have any duplication?
Right now the "limit" flag it's compared to a percentage of duplication, and only accepts integers.
If i run jscpd with --limit 0 it fails also when no duplication exists.

`Found 0 exact clones with 0 duplicated lines in 0 files
 0.00% (0 lines) duplicated lines out of 3464 total lines of code.
ERROR: jscpd found too many duplicates over threshold
`

**Comment by kucherenko** [comment]
thank you, will fix it

**Comment by kucherenko** [comment]
fixed in jscpd@0.6.2
