### ISSUE TITLE
Detect clones in main directory and a number of diffenrent directories.

### ISSUE THREAD

**Issue by Kakadu** [kucherenko/jscpd#491]
**Is your feature request related to a problem? Please describe.**
Imagine  a setup where we have a number of directories: A,B,C,D,... and we want to find clones between (for example) directory A and directories B,C,D. If we write `npx jscpd A B C D` it will find clones between B and C too, and we want to avoid that. 

**Describe the solution you'd like**
It would be great to have a command switch that will specify 'main' location of the sources  and jscpd will try to find clones between the main location and a number of other locations

**Describe alternatives you've considered**
I know a finite list of other directories. It looks like that I can do multiple invocations like `npx jscpd A B`, `npx jscpd A C`, etc.,  and in the end merge HTML results (I hope they will be mergable). But I want to start by asking: is there a more simple solution?

**Comment by kucherenko** [comment]
Thank you for the report, have you seen skip local option? Please let me know if you can solve your issue with the option https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#skip-local

**Comment by Kakadu** [comment]
> Thank you for the report, have you seen skip local option? Please let me know if you can solve your issue with the option https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#skip-local

I have seen this switch but `jscpd   --skipLocal A B C` search for clones between A&B, A&C, B&C, but I want only for clone between A&B and A&C

**Comment by zodman** [comment]
close this solved!
