### ISSUE TITLE
Sourcemap doesn't work

### ISSUE THREAD

**Issue by fengzilong** [kucherenko/jscpd#499]
**Describe the bug**

Sourcemap from `@jscpd/core` doesn't work, and source code is missing in chrome devtools "Source" panel

**To Reproduce**

Use chrome devtools to debug `@jscpd/core`

**Expected behavior**

See the source code of `detector.ts`

**Screenshots**

![image](https://user-images.githubusercontent.com/9125255/141605245-a8106af9-74b6-48ee-a077-8be357245fcb.png)

**Desktop (please complete the following information):**
 - OS:  MacOS
 - OS Version 10.13.6
 - NodeJS Version v16.8.0
 - jscpd version @jscpd/core@3.4.1

**Comment by kucherenko** [comment]
thank you, will try to fix it

**Comment by kucherenko** [comment]
fixed at jscpd@4.0.4
