### ISSUE TITLE
html reporter for windows can not render properly

### ISSUE THREAD

**Issue by dhlolo** [kucherenko/jscpd#538]
**Describe the bug**

**To Reproduce**
1. get report html file but `index.html` can not render properly in browser

**Expected behavior**
![image](https://user-images.githubusercontent.com/50065494/189062178-d4d83f58-4d6d-4e31-8d47-44faea8cca7d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/50065494/189062472-8d6a47be-e09a-4e0a-8d08-0521d8af736d.png)

**Desktop (please complete the following information):**
 - OS: windows
 - OS Version: 10
 - NodeJS Version: 14.18.0
 - jscpd version:  3.4.5

**Additional context**
--

**Comment by dhlolo** [comment]
I tried in other colleague's mac, it can render as expected.

**Comment by tibic** [comment]
i have this problem
![image](https://user-images.githubusercontent.com/6113239/192719921-4959a377-9164-40c3-92f1-6b4266d254c6.png)

**Comment by tibic** [comment]
My Windows computer has the same problem

**Comment by kucherenko** [comment]
fixed with a new reporter at jscpd@3.5.8
