### ISSUE TITLE
Add Support for .mjs .cjs files being picked up as .js files

### ISSUE THREAD

**Issue by a0n** [kucherenko/jscpd#544]

**Comment by kucherenko** [comment]
good point, will add

**Comment by chimurai** [comment]
Piggybacking on this issue.

Similarly, TypeScript added support for `.mts` and `.cts`.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#new-file-extensions

If needed, I can open a new issue to track it separately.

**Comment by kucherenko** [comment]
Implemented at jscpd@3.5.1
