### ISSUE TITLE
I have created a github action for jscpd

### ISSUE THREAD

**Issue by oadam** [kucherenko/jscpd#565]
Just a heads up to let you know that I've created a [github action](https://github.com/marketplace/actions/pull-requests-jscpd) that annotates pull requests to flag modified code that contains duplications according to jscpd
Here is a screenshot of it in action in my private repo :
![image](https://user-images.githubusercontent.com/1640493/208080722-199122c2-40dc-46f7-801a-e31c6b49fa2c.png)

Not much else to say, thank you for your work !

**Comment by kucherenko** [comment]
thank you for the action, feel free to add a link to the README file here - https://github.com/kucherenko/jscpd#who-uses-jscpd
