### ISSUE TITLE
NPM page needs updating

### ISSUE THREAD

**Issue by joshuambg** [kucherenko/jscpd#574]
**Describe the bug**
The docs seem outdated. 
https://www.npmjs.com/package/jscpd

**To Reproduce**
Docs say:
`consoleFull - report about clones to console with blocks of code;`
Command:
`npx jscpd src --pattern '**/*.tsx' --reporters 'consoleFull'`
Does not output 'consoleFull'

**Expected behavior**
Should display output as `'consoleFull'`

**To Reproduce**
Docs say:
`Default: ./report/`
Command:
`npx jscpd src -o --pattern '**/*.tsx' --reporters 'html'`
Error:
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)`

**Expected behavior**
Should default to `./report/`

**Desktop (please complete the following information):**
 - NodeJS Version `v14.17.3`
 - jscpd version `3.5.3`

**Additional context**
Please check all commands and update docs, not just ones listed here. This is expected behavior? Make docs more clear. Thanks!

**Comment by kucherenko** [comment]
Hello!
I am ready to answer your questions: with jscpd v4 `consoleFull` works fine, regarding option -o - the default option should work when you don't use -o in the command line, in case of using `npx jscpd src -o ...` argument parser expect that output dir will be provided as a next argument
