### ISSUE TITLE
getting OOM issue while executing jscpd for more than 5000 files

### ISSUE THREAD

**Issue by Sudharshan45** [kucherenko/jscpd#587]
<img width="1057" alt="Screenshot 2023-05-04 at 5 36 32 PM" src="https://user-images.githubusercontent.com/68746234/236200118-f55c5ddc-2105-4263-9b2b-66b74a79fefa.png">

I runned for 20000 files and i am getting above error

**Comment by kucherenko** [comment]
try to use @jscpd/leveldb-store for the repo

**Comment by Sudharshan45** [comment]
<img width="1057" alt="Screenshot 2023-05-04 at 7 12 31 PM" src="https://user-images.githubusercontent.com/68746234/236223825-840e965a-e2be-4a1f-a5d7-e647e8258a75.png">
in above image i tried with npx jscpd [repo_path] --store,  teriminal what value need to give to --store?

**Comment by kucherenko** [comment]
you should install @jscpd/leveldb-store and call with `--store leveldb` option
