### ISSUE TITLE
Allow repeated command-line options.

### ISSUE THREAD

**Issue by diegocr** [kucherenko/jscpd#59]
For example, to provide multiple --exclude rules, e.g:

`jscpd -e **/node_modules/** -e **/vendor/** ...`

Currently only the last one is taken.

**Comment by kucherenko** [comment]
thank you for issue, will investigate it

**Comment by wavded** [comment]
Any movement on this?

**Comment by guenam** [comment]
I'd love that option too

**Comment by kucherenko** [comment]
This functionality will be in jscpd@1.x, I have plan to release it in September

**Comment by blatinier** [comment]
Any news on that?

**Comment by kucherenko** [comment]
I have some limitation of options parser library, currently you can use .cpd.yaml file for that

**Comment by blatinier** [comment]
Yes I saw it with further digging.
Here is the related issue in the `cli` library: https://github.com/node-js-libs/cli/issues/62

**Comment by kucherenko** [comment]
The version 1.0.0 of jscpd supports `,` as the separator for multi options
