### ISSUE TITLE
Not reporting duplicate code in different file types

### ISSUE THREAD

**Issue by ssivanatarajan** [kucherenko/jscpd#592]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I am running a jscpd for a css and less file both are having some duplicate code  . but it is not reported in JSCPD .  can we check the duplicate with different types .

**Screenshots**

**Desktop (please complete the following information):**
 - OS:MAC 
 - OS Version 12.6.5
 - NodeJS Version 14.18.3
 -   jscpd version : 3.5.9

<img width="411" alt="Screenshot 2023-06-28 at 6 41 46 AM" src="https://github.com/kucherenko/jscpd/assets/8462498/e793e91a-6a48-4bb5-a301-94f61d3a002b">
<img width="546" alt="Screenshot 2023-06-28 at 6 41 53 AM" src="https://github.com/kucherenko/jscpd/assets/8462498/2ed3b094-089a-4a84-8d59-04a740c8ba98">
<img width="822" alt="Screenshot 2023-06-28 at 6 42 12 AM" src="https://github.com/kucherenko/jscpd/assets/8462498/01c3bffa-c43f-4a3a-906f-a3dba48ad77e">

**Additional context**

**Comment by kucherenko** [comment]
Hi @ssivanatarajan 
In general, it is different formats and that is why jscpd ignores duplication. Before your issue, it is expected behavior.
I'll try to rethink this behavior and make options for the case.
