### ISSUE TITLE
Sarif support

### ISSUE THREAD

**Issue by dragosv** [kucherenko/jscpd#598]
**Is your feature request related to a problem? Please describe.**
SARIF is an OASIS Standard for static analysis alerts. GitHub/Azure DevOps support uploading SARIF formatted alerts.

**Describe the solution you'd like**
Add sarif as one of the available reporters

**Additional context**
https://sarifweb.azurewebsites.net/
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github
https://github.com/microsoft/sarif-azuredevops-extension

**Comment by kucherenko** [comment]
thank you, will add

**Comment by kucherenko** [comment]
The report was added in jscpd@4.0.4
