### ISSUE TITLE
--format Invalid Configuration

### ISSUE THREAD

**Issue by livelyPeng** [kucherenko/jscpd#603]
![image](https://github.com/kucherenko/jscpd/assets/32978177/c6825321-bca1-4960-ab04-6f15be96e51a)

Through debugging, it was found that the configuration of format is not included in the options section

![img_v2_58a82c88-04af-44bd-a896-8439b044ee0g](https://github.com/kucherenko/jscpd/assets/32978177/984c8ebe-7730-459c-a013-8794ebb00468)

![image](https://github.com/kucherenko/jscpd/assets/32978177/a534688a-a719-428e-9e0f-9ec415ea8e49)

**Comment by livelyPeng** [comment]
Seeking help with urgent issues, thank you

**Comment by livelyPeng** [comment]
![image](https://github.com/kucherenko/jscpd/assets/32978177/4ae27c68-e462-4184-a6f8-d9daecac5249)
Why is the official configuration parameter empty?

**Comment by kucherenko** [comment]
`jscpd()` is used as cli handler, which is why the first argument is `process.argv`
