### ISSUE TITLE
More documentation on building, running, and debugging

### ISSUE THREAD

**Issue by NimaiMalle** [kucherenko/jscpd#616]
The **Start Contribution** section describes how to initialize and build the project, and how to run the tests, but not how to run the built jscpd cli.

Please add instructions on how to run the built command line tool, specifically how to launch and debug the tool.

I have been trying to create a working Visual Studio Code debug launch configuration, but have been running into all sorts of issues about module resolution, etc.

Thank you!

**Comment by kucherenko** [comment]
In the jscpd@4.0.x the build process is much easier and not you can run just 

```
pnpm build
```
in the root of the project and get results.

Also you can run `pnpm dev` and work with jscpd continuously with watching directory.
