### ISSUE TITLE
Able to compare two project between them

### ISSUE THREAD

**Issue by mathias22osterhagen22** [kucherenko/jscpd#620]
**Is your feature request related to a problem? Please describe.**
It would be great to have the possibility to check identical code between two projects. 

**Describe the solution you'd like**
`npx jscpd project01/src project02/src`
Would perform a check from the src of project01 against the src of project02 and not check for duplicate in project01.

**Describe alternatives you've considered**
None.

**Additional context**
Could help to justify/identify: 
- Cheat (copy) between students
- Stolen code from college
- Shared code between project that could be regrouped
- etc...

**Comment by kucherenko** [comment]
Hi, the feature has already been implemented, you can read more about `--skipLocal` option.

https://github.com/kucherenko/jscpd/tree/master/packages/jscpd#skip-local

or just run the following command:

```
npx jscpd --skipLocal project01/src project02/src
```
