### ISSUE TITLE
can not find module 'jscpd'.  version4.04

### ISSUE THREAD

**Issue by hasmokan** [kucherenko/jscpd#660]
version 4.04 
node version 16.20.0

## I ran into this problem when I used jscpd's api. 
![image](https://github.com/kucherenko/jscpd/assets/112612128/ab4bf914-3f06-4d1d-af39-45157bf52e49)
## version 3.38, it work well.
![image](https://github.com/kucherenko/jscpd/assets/112612128/ee414b35-2e2a-46e3-b8ca-5a3958b44cfb)

it is bug?

**Comment by kucherenko** [comment]
hm... interesting, will check

**Comment by kucherenko** [comment]
fixed at jscpd v4.0.5
