### ISSUE TITLE
Support Vue.js template files

### ISSUE THREAD

**Issue by alex-frameio** [kucherenko/jscpd#69]
Feature request for Vue.js .vue file template support.

**Comment by kucherenko** [comment]
added at jscpd@0.6.9

**Comment by service-paradis** [comment]
Not listed in https://github.com/kucherenko/jscpd/blob/HEAD/docs/supported_formats.md

Is this really supported?

**Comment by kucherenko** [comment]
Hello, yes vue supported, but in jscpd > 1.0 it is not separate format, in report you will see "markup" for <template> tag in vue, js/ts for <script> and css/scss for <style> tag

**Comment by service-paradis** [comment]
Great, thanks!
Will give it a try!
