### ISSUE TITLE
crypto package clashes with nodes internal crypto package 

### ISSUE THREAD

**Issue by mimaidms** [kucherenko/jscpd#70]
It seems that the crypto package you use to create md5 hashes clashes with the package which comes with node.js.

Since npm (>= v3.0.0 i think) installs all packages on the highest level possible, there is in the root node_modules directory the crypto package you use.

At least on our dev systems with devPackages installed (gulp-jscpd which usses jscpd) we can't use nodes own crypto package

Is it possible that you can use another package to create the md5 hashes (e.g. md5)

If have no idea how to solve this issue, only to not use the jscpd code checker. Or is there a way to require the node internal package (i didn't found any)?

Regards

**Comment by mimaidms** [comment]
Hm, i am not so shure what happens here. But i think it is an node6 issue. sorry to bother you.

**Comment by kucherenko** [comment]
(y) np
