### ISSUE TITLE
.cpd.yaml not working (bad merge logic)

### ISSUE THREAD

**Issue by ainthek** [kucherenko/jscpd#74]
if you specify languages in .yaml file that will be ignored, and overridden by CLI params, and since CLI params have defaults it does not work.

see comments below,

prepareOptions = function(options, config) {

// options is from CLI, languages is full array with all languages
  var key, optionsNew, value;
 // this is ok merges defaults with specified on confif file, config file wins
  optionsNew = _.extend(optionsPreprocessor["default"], config);

  for (key in options) {
    value = options[key];
    if (!(value === null)) {
      optionsNew[key] = value; // !!! BUG this overwrites config with CLI specified defaults
    }
  }
  if (typeof optionsNew.languages === 'string') {
    optionsNew.languages = optionsNew.languages.split(',');
  }

  optionsNew.extensions = TokenizerFactory.prototype.getExtensionsByLanguages(optionsNew.languages);
  return optionsNew;
};

to fix this remove defaults from CLI ?
"languages": ['g', "list of languages which scan for duplicates, separated with comma", "string", Object.keys(TokenizerFactory.prototype.LANGUAGES).join(',')], and keep them only in

optionsPreprocessor["default"] = {
    languages: Object.keys(TokenizerFactory.prototype.LANGUAGES),
    verbose: false,
    debug: false,
    files: null,
    exclude: null,
    "min-lines": 5,
    "min-tokens": 70
  };

**Comment by kucherenko** [comment]
I got it, will fix

**Comment by ainthek** [comment]
Status please ?

**Comment by kucherenko** [comment]
fixed in scope of #75 and available in jscpd@0.6.7
