### ISSUE TITLE
How to configute extensions for language ?

### ISSUE THREAD

**Issue by ainthek** [kucherenko/jscpd#75]
This line seems to deny any chances to set file extensions from congif file.

optionsNew.extensions = TokenizerFactory.prototype.getExtensionsByLanguages(optionsNew.languages);

we need a option to parametrize language->extension map

Thanx

**Comment by kucherenko** [comment]
thank you for your tickets, I will fix this

**Comment by ainthek** [comment]
Please,

**Comment by kucherenko** [comment]
sorry for delay, I hope I will close all of issues during Christmas Holidays, sorry again

**Comment by kucherenko** [comment]
You can use parameter `languages-exts` like here
jscpd --languages-exts javascript:es5,es6,es7,js;php:php5

this function added at jscpd@0.6.7
