### ISSUE TITLE
.cpd.yaml is not working properly

### ISSUE THREAD

**Issue by KMahesh045** [kucherenko/jscpd#91]
If I execute **jscpd**  through `jscpd --files "src/app/user/*.ts"` it takes the files from exact specifid path and it shows the following details. ((i.e) It shows 31 files are duplicated )

> info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
> info:    Preprocessors running time: durationMs=21
> info:    Scanning 31 files for duplicates...
> info:    Scanning for duplicates time: durationMs=505
> info:    Scanning... done!
> 
> info:    Start report  #generation...
> 
> info:    Found 29 exact clones with 617 duplicated lines in 18 files

But If I run this using **.cpd.yaml** it takes 0 files.

This is my .cpd.yaml file content:
```
languages:
  -"typescript"

path:"src/app/user"

files:
  -"src/app/user/**/*.ts"

reporter: json

output: "Duplicate_Report.json"
```
**_Log_**
> info:    jscpd - copy/paste detector for programming source code, developed by Andrey Kucherenko
> info:    Preprocessors running time: durationMs=11
> info:    Scanning for duplicates time: durationMs=38
> info:    Scanning... done!
> 
> info:    Start report generation...
> 
> info:    Found 0 exact clones with 0 duplicated lines in 0 files
> 
> 
>  0.00% (0 lines) duplicated lines out of 0 total lines of code.
> 
> info:    Generate report time: durationMs=8
> info:    All time: durationMs=63

correct me if I made anything wrong.

**Comment by evertheylen** [comment]
I have exactly the same problem: whatever I try, loading a config file will always produce 0 results.

**Comment by kucherenko** [comment]
Hello,

I'm sorry for late answer. 

You have path option pointed to `src/app/user/**/*.ts` and try to find files `src/app/user/**/*.ts` if we concat this we have files path like `src/app/user/src/app/user/**/*.ts`.

Try to change path or files options for point right place to the files.

Thank you
