### ISSUE TITLE
Lua Code Duplication Detection

### ISSUE THREAD

**Issue by hchow77** [kucherenko/jscpd#97]
Been googling around for a Code Duplication Detection tool that works on lua code, but haven't been able to find one. Was wondering if you would consider adding support for lua. Seemed that given the list of languages that you currently support, adding lua seemed to be reasonable.

Thanks for the consideration!

**Comment by kucherenko** [comment]
Thank you, I will add Lua

**Comment by hchow77** [comment]
Great. Thanks!

**Comment by kucherenko** [comment]
added in jscpd@0.6.13
